const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
$('.nav-toggle')?.addEventListener('click',()=>$('.nav')?.classList.toggle('open'));
const page=document.body.dataset.page;$$('.nav a').forEach(a=>{if(a.getAttribute('href')?.includes(page)||page==='home'&&a.getAttribute('href')==='index.html')a.classList.add('active')});
function tick(){const el=$('#countdown');if(!el)return;const target=new Date('2026-11-19T00:00:00Z');const diff=target-new Date();if(diff<=0){el.textContent='Launch window active';return}const d=Math.floor(diff/864e5),h=Math.floor(diff/36e5)%24,m=Math.floor(diff/6e4)%60;el.textContent=`${d} days • ${h} hours • ${m} mins`}tick();setInterval(tick,60000);
const areas={
 'Vice City':{type:'Confirmed area',img:'assets/images/shot-vice-city-01.jpg',body:'The main urban destination. Build pages for districts, landmarks, shops, routes and activity guides here.',link:'areas.html#vice-city'},
 'Leonida Keys':{type:'Confirmed area',img:'assets/images/shot-leonida-keys-01.jpg',body:'Island roads, bridges, water travel and scenic routes. Good future page for exploration and vehicle testing.',link:'areas.html#leonida-keys'},
 'Grassrivers':{type:'Confirmed area',img:'assets/images/shot-grassrivers-01.jpg',body:'Wetlands and rural travel. This can become a wildlife, route and side-activity guide once details are confirmed.',link:'areas.html#grassrivers'},
 'Port Gellhorn':{type:'Confirmed area',img:'assets/images/shot-port-gellhorn-01.jpg',body:'Coastal resort style area. Useful for future map pins, activities and route guides.',link:'areas.html#port-gellhorn'},
 'Ambrosia':{type:'Confirmed area',img:'assets/images/shot-ambrosia-01.jpg',body:'Industrial and inland area watchlist. Add confirmed points of interest as more information appears.',link:'areas.html#ambrosia'},
 'Mount Kalaga':{type:'Confirmed area',img:'assets/images/shot-mount-kalaga-01.jpg',body:'Northern outdoor region watchlist. Good future category for exploration and hidden locations.',link:'areas.html#mount-kalaga'}
};
function setMap(name){const p=$('#mapPanel');if(!p||!areas[name])return;const a=areas[name];p.innerHTML=`<span class="tag note">${a.type}</span><h2>${name}</h2><p>${a.body}</p><a class="btn primary" href="${a.link}">Open area guide</a>`}$$('.pin').forEach(b=>b.addEventListener('click',()=>setMap(b.dataset.area)));setMap('Vice City');
const q=$('#areaSearch');if(q)q.addEventListener('input',()=>{const v=q.value.toLowerCase();$$('.area-card').forEach(c=>c.classList.toggle('hidden',!c.textContent.toLowerCase().includes(v)))});
$$('.tab').forEach(t=>t.addEventListener('click',()=>{const group=t.dataset.group;$$(`.tab[data-group="${group}"]`).forEach(x=>x.classList.remove('active'));t.classList.add('active');$$(`[data-panel="${group}"]`).forEach(p=>p.classList.toggle('hidden',p.id!==t.dataset.target))}));
$$('.gallery-grid img').forEach(img=>img.addEventListener('click',()=>{const w=window.open(img.src,'_blank');w?.focus()}));